[config]
version_check = false

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.hyprlua]
input_path = "~/.config/matugen/templates/colors.lua"
output_path = "~/.config/hypr/configs/colors.lua"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "~/.config/matugen/scripts/gtk-themes-reload.sh"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.qt]
input_path = "~/.config/matugen/templates/Matugen.colors"
output_path = "~/.local/share/color-schemes/Matugen.colors"

[templates.swaync]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "command -v swaync-client >/dev/null && swaync-client -rs || true"

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode.json"
output_path = "~/.config/Code/User/colors.json"
post_hook = "~/.config/matugen/scripts/vscode.sh"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.local/state/quickshell/generated/colors.json"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.obs]
input_path = '~/.config/matugen/templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'
