source = ~/.config/hypr/colors.conf

background {
    monitor =
    path = screenshot
    blur_passes = 5
    blur_size = 1
    brightness = 0.6
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $primary
    font_size = 140
    font_family = Nunito ExtraBold
    position = 0, 235
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $secondary
    font_size = 140
    font_family = Nunito ExtraBold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = $on_surface_variant
    font_size = 18
    font_family = Nunito
    position = 0, -20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = $surface_container_highest
    font_color = $on_surface
    rounding = -1
    placeholder_text = 󰌾  Password...
    position = 0, -380
}