_G.mainMod = "SUPER"
_G.terminal = "kitty"
_G.fileManager = "dolphin"

hl.config({
    autogenerated = false,
    misc = {
        disable_hyprland_logo = true,
        middle_click_paste = false
    }
})

require("configs.env")
require("configs.keybinds")
require("configs.monitors")
require("configs.colors")
require("configs.tags")
require("configs.rules")
require("configs.design")
require("configs.input")
require("configs.execs")
