[General]
background=$HOME/.config/hypr/current_wall

primaryColor={{colors.primary.default.hex}}
accentColor={{colors.secondary.default.hex}}
backgroundColor={{colors.background.default.hex}}
textColor={{colors.on_background.default.hex}}

fontFamily=Google Sans Flex Freeze
fontSize=12